### ISSUE TITLE
Create fully-dressed format use cases for the features that will exist in the first milestone's deliverable

### ISSUE THREAD

**Issue by gokhanustuner** [ossarioglu/SWE574-SWEet_Dewarriors#25]
Fully-dressed format use cases must be written for the features that will be primarily implemented.

- [x] **Take Service** use case.
- [x] **Create Service** use case.
- [x] **Create Event** use case.

**Comment by gokhanustuner** [comment]
To view the use cases click on the link below

[https://github.com/ossarioglu/SWE574-SWEet_Dewarriors/wiki/Use-Case-Model](https://github.com/ossarioglu/SWE574-SWEet_Dewarriors/wiki/Use-Case-Model)
